{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-io-bytestring/0.7.0/kotlinx-io-bytestring-0.7.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-io-bytestring",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-bytestring-jvm-0.7.0.jar",
          "url": "kotlinx-io-bytestring-jvm-0.7.0.jar",
          "size": 22690,
          "sha512": "646ada4367044be8d051aff3eb9424e6dffdb7bb95ddff2f95d5f0f51f652e0b33662779eab02a0e9317676f9647dd684e10fafaae26af46d60cfa6226c45d19",
          "sha256": "ea38a66b0ff46ed82dded9e81d2dce70e5fbe03bd6cc52b4fc8869381dea7b7d",
          "sha1": "ffe5bd231da40d21870250703326113277dbf9c3",
          "md5": "9434df76e0f1c6cf99a27a3375d87469"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-bytestring-jvm-0.7.0.jar",
          "url": "kotlinx-io-bytestring-jvm-0.7.0.jar",
          "size": 22690,
          "sha512": "646ada4367044be8d051aff3eb9424e6dffdb7bb95ddff2f95d5f0f51f652e0b33662779eab02a0e9317676f9647dd684e10fafaae26af46d60cfa6226c45d19",
          "sha256": "ea38a66b0ff46ed82dded9e81d2dce70e5fbe03bd6cc52b4fc8869381dea7b7d",
          "sha1": "ffe5bd231da40d21870250703326113277dbf9c3",
          "md5": "9434df76e0f1c6cf99a27a3375d87469"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-io-bytestring-jvm-0.7.0-sources.jar",
          "url": "kotlinx-io-bytestring-jvm-0.7.0-sources.jar",
          "size": 13230,
          "sha512": "f6dbd0bc8da22d91c8720ba35b51ba5da3a143a56a16401d757156b06b7c83d7440ed5a03174c0cfdf4cd271bad3de1608109a2c28cd03850f72659022f03922",
          "sha256": "e56a4af58013c739480fb1305224e9af2816b4c7add27db4adc291da7ea403c5",
          "sha1": "fa5686c74b26c4f1f288000a39f9218322f3ca2a",
          "md5": "a5f9a39157602694ee507e572397b112"
        }
      ]
    }
  ]
}
