{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-cio/3.1.3/ktor-client-cio-3.1.3.module",
    "group": "io.ktor",
    "module": "ktor-client-cio",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-cio-jvm-3.1.3.jar",
          "url": "ktor-client-cio-jvm-3.1.3.jar",
          "size": 109299,
          "sha512": "ad0f725a2817835dec8ec31af61d280c029b435f6f28d5bb66d531d908a18529b6a25960bed5aa68332983a8f144352e8bf9a91b223a58ef7408902a34705b24",
          "sha256": "9a86341588057a23d3ba4562fdc8afcef6facd071678a0c20b3b28a19ec35c88",
          "sha1": "7a475976a04a18e5a28aae74c6d1d3bfac32bf3f",
          "md5": "95a2cff854d3994339bbb91280a8ead8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-cio-jvm-3.1.3.jar",
          "url": "ktor-client-cio-jvm-3.1.3.jar",
          "size": 109299,
          "sha512": "ad0f725a2817835dec8ec31af61d280c029b435f6f28d5bb66d531d908a18529b6a25960bed5aa68332983a8f144352e8bf9a91b223a58ef7408902a34705b24",
          "sha256": "9a86341588057a23d3ba4562fdc8afcef6facd071678a0c20b3b28a19ec35c88",
          "sha1": "7a475976a04a18e5a28aae74c6d1d3bfac32bf3f",
          "md5": "95a2cff854d3994339bbb91280a8ead8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-client-cio-jvm-3.1.3-sources.jar",
          "url": "ktor-client-cio-jvm-3.1.3-sources.jar",
          "size": 18219,
          "sha512": "4face343354b2d5903bd2f9b8eb71f67c3622ab530bfd15c1b91d9bfdff8f5191d7d1675cfb31cce8e21c6ba9a5b01b9bd25d5647020f38e0dce06cd617ebf67",
          "sha256": "05d09d79cd1902de9ddffd3e430363ad7ffd7017c0a62a0ec4f56974f85f2844",
          "sha1": "2440cf949aad56038c3498842c7f26479805338b",
          "md5": "0d3c2703f7c5c85b3029b4147d3f715e"
        }
      ]
    }
  ]
}
