{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-tx",
    "version": "6.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.2.6.jar",
          "url": "spring-tx-6.2.6.jar",
          "size": 285385,
          "sha512": "fcd0d975d71a5f95047a22fe584f1cb0a408caab585aa54ff0dfaf0c707213be623809dc05d070c160857af8f3d88f8b13ebc3a1c105be62ebbfca0d7cd9fe62",
          "sha256": "98c8b59a2f59b575e166577316d6d0608c63d59592c502528ff6853ef639dfed",
          "sha1": "fb46b2d651a6c509625bc6e7e38865137f658eca",
          "md5": "f2479aabdea6572c5721e15611c40838"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.2.6.jar",
          "url": "spring-tx-6.2.6.jar",
          "size": 285385,
          "sha512": "fcd0d975d71a5f95047a22fe584f1cb0a408caab585aa54ff0dfaf0c707213be623809dc05d070c160857af8f3d88f8b13ebc3a1c105be62ebbfca0d7cd9fe62",
          "sha256": "98c8b59a2f59b575e166577316d6d0608c63d59592c502528ff6853ef639dfed",
          "sha1": "fb46b2d651a6c509625bc6e7e38865137f658eca",
          "md5": "f2479aabdea6572c5721e15611c40838"
        }
      ]
    }
  ]
}
