{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jdbc",
    "version": "6.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-6.2.6.jar",
          "url": "spring-jdbc-6.2.6.jar",
          "size": 472297,
          "sha512": "f5daf021ac71aa9f02e4b9be5754419e8bbc5d7cdb889e108b74eae1e19310c9ec8a5c97cb8331681532c9d4b9c6671dee93e8067071a603e4fe6268ce77d099",
          "sha256": "9672785a9e50ae653f2da218cee924eb31b016948896bc221eae28a22085447e",
          "sha1": "529137b0f92d8cfd13876e6aa8df9088246b4755",
          "md5": "5493ef33371d0e36f34da81e9475c38f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-6.2.6.jar",
          "url": "spring-jdbc-6.2.6.jar",
          "size": 472297,
          "sha512": "f5daf021ac71aa9f02e4b9be5754419e8bbc5d7cdb889e108b74eae1e19310c9ec8a5c97cb8331681532c9d4b9c6671dee93e8067071a603e4fe6268ce77d099",
          "sha256": "9672785a9e50ae653f2da218cee924eb31b016948896bc221eae28a22085447e",
          "sha1": "529137b0f92d8cfd13876e6aa8df9088246b4755",
          "md5": "5493ef33371d0e36f34da81e9475c38f"
        }
      ]
    }
  ]
}
