org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.vfs.watch=true
org.gradle.jvmargs=-Xms512m -Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseG1GC -Dfile.encoding=UTF-8
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kapt.incremental.apt=true
