{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-websockets/3.1.3/ktor-websockets-3.1.3.module",
    "group": "io.ktor",
    "module": "ktor-websockets",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-jvm-3.1.3.jar",
          "url": "ktor-websockets-jvm-3.1.3.jar",
          "size": 167911,
          "sha512": "c91d9b6425fc51a1407711bd5677d243bd557ca41f5695742a61b66e216c5ad709d369b268d9acfe27f2f98cb772db278023bbe802286b20a602909104be59e8",
          "sha256": "ef28b4f12054ee125765b72fe3230e215a60b73b2ff2072a5c280fcf09329077",
          "sha1": "0ba5d56f7ecfd3347b351dcc3bfd519233aaa22b",
          "md5": "53caf5d74ee0177542236957715963b5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-jvm-3.1.3.jar",
          "url": "ktor-websockets-jvm-3.1.3.jar",
          "size": 167911,
          "sha512": "c91d9b6425fc51a1407711bd5677d243bd557ca41f5695742a61b66e216c5ad709d369b268d9acfe27f2f98cb772db278023bbe802286b20a602909104be59e8",
          "sha256": "ef28b4f12054ee125765b72fe3230e215a60b73b2ff2072a5c280fcf09329077",
          "sha1": "0ba5d56f7ecfd3347b351dcc3bfd519233aaa22b",
          "md5": "53caf5d74ee0177542236957715963b5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-websockets-jvm-3.1.3-sources.jar",
          "url": "ktor-websockets-jvm-3.1.3-sources.jar",
          "size": 34576,
          "sha512": "8d310502f44ea200e41b918cf88f31022ee18955c65a531c3862f9bc45336c880af59d850fe7a6b9d36dfea560e51dd08934ab939b1d692204b4b7db1116466e",
          "sha256": "300dd6bb2bb9a32aab0c84fd7a190980e7f908919a31e489eafc20ab72b0e662",
          "sha1": "5ff6f6a804014c981037bc84e5a2c756d7749480",
          "md5": "386bb1a9232ed81fffcf938948b2f434"
        }
      ]
    }
  ]
}
