{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "6.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.2.6.jar",
          "url": "spring-test-6.2.6.jar",
          "size": 1024225,
          "sha512": "7db0211bbdcf30b77c83aec13da55996d2400bab0f958c155eccd241d734018acaf565d6527ec074dd417609f454a360f25241046b564cfaf830797d960778fb",
          "sha256": "bbeb8806985dca16892e69445b9e527c1525ed5a9b66c398dab978ff5402c9a5",
          "sha1": "1f1d95749dca9a7535f0ba51e1dfdbf987bebcf1",
          "md5": "99906855a3d97570e4bbb24cf340f680"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.2.6.jar",
          "url": "spring-test-6.2.6.jar",
          "size": 1024225,
          "sha512": "7db0211bbdcf30b77c83aec13da55996d2400bab0f958c155eccd241d734018acaf565d6527ec074dd417609f454a360f25241046b564cfaf830797d960778fb",
          "sha256": "bbeb8806985dca16892e69445b9e527c1525ed5a9b66c398dab978ff5402c9a5",
          "sha1": "1f1d95749dca9a7535f0ba51e1dfdbf987bebcf1",
          "md5": "99906855a3d97570e4bbb24cf340f680"
        }
      ]
    }
  ]
}
