{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator",
    "version": "3.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-3.4.5.jar",
          "url": "spring-boot-actuator-3.4.5.jar",
          "size": 698207,
          "sha512": "79a0048c03fe63ec38eb196f3f32c4365f67b620b7772811f760bf728844c017f3eef2c824ccaf5c6c79f685cad725c8b689b3757b31e1c58f3ac5bd6fa379c2",
          "sha256": "407dd87c8966e1a9f4bd32cd84ebee01928f10d1e60249d884b32b1d00a28deb",
          "sha1": "605c2f057a4c204f247198a7ddedbf4b03131df1",
          "md5": "cb82f42b62b3609913072b31145cae23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-3.4.5.jar",
          "url": "spring-boot-actuator-3.4.5.jar",
          "size": 698207,
          "sha512": "79a0048c03fe63ec38eb196f3f32c4365f67b620b7772811f760bf728844c017f3eef2c824ccaf5c6c79f685cad725c8b689b3757b31e1c58f3ac5bd6fa379c2",
          "sha256": "407dd87c8966e1a9f4bd32cd84ebee01928f10d1e60249d884b32b1d00a28deb",
          "sha1": "605c2f057a4c204f247198a7ddedbf4b03131df1",
          "md5": "cb82f42b62b3609913072b31145cae23"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-3.4.5-javadoc.jar",
          "url": "spring-boot-actuator-3.4.5-javadoc.jar",
          "size": 1505728,
          "sha512": "b41742711d8bbb8ab92187d304e1ba9b5e449efde54f2b3551b028f859d4970f73384e75854b6c3c6fae1c5eb30332d55c389e16b4a6b99327736bdaa228707a",
          "sha256": "bdfad63a76e4438e5dd2b5fae6d9f8f22fd5e721ccce9423d8037724ead7263b",
          "sha1": "370576c430c049aa2e7f58f39e2be9c56a86ffc4",
          "md5": "ba50fbf1f0ae739b93d4c4482288ee1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-3.4.5-sources.jar",
          "url": "spring-boot-actuator-3.4.5-sources.jar",
          "size": 469119,
          "sha512": "37b0f2646b64f02c6041cf250047e4081b8d0e8ef818b5c2a5a3681462a6afe566c093976d2bf2a34b6da5a239df76b6ba56eac7256338a6b6fad33a59f7c953",
          "sha256": "cbaf096ffc539dd172e4113b1996f513855bbb6c91a3180287205bdd0286ac2d",
          "sha1": "cea635af9501958089088d01859e8846367b2cbd",
          "md5": "a01d1029dac5746bc59379d8c39687d5"
        }
      ]
    }
  ]
}
