{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "3.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.4.5.jar",
          "url": "spring-boot-test-3.4.5.jar",
          "size": 253724,
          "sha512": "7eed6128ed029d9bacb898c5fd427d9de619cf8b7fcadc1414ab7dcec85c60014142e2147b6b7b5972adc38effb540533b8264864c25ddd6b423d45e90356a64",
          "sha256": "5d2060d923da330cbc05edd3174496a5144ee3edda424c785338d88c7b3b0114",
          "sha1": "5029e995e6d69785f3125ba9ea043490b80cbe83",
          "md5": "e5a3ddaee3855b025e0dcc4f68a2e9a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.4.5.jar",
          "url": "spring-boot-test-3.4.5.jar",
          "size": 253724,
          "sha512": "7eed6128ed029d9bacb898c5fd427d9de619cf8b7fcadc1414ab7dcec85c60014142e2147b6b7b5972adc38effb540533b8264864c25ddd6b423d45e90356a64",
          "sha256": "5d2060d923da330cbc05edd3174496a5144ee3edda424c785338d88c7b3b0114",
          "sha1": "5029e995e6d69785f3125ba9ea043490b80cbe83",
          "md5": "e5a3ddaee3855b025e0dcc4f68a2e9a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.4.5-javadoc.jar",
          "url": "spring-boot-test-3.4.5-javadoc.jar",
          "size": 418958,
          "sha512": "c5076dff3aa851010e194ec752d5656bbf0cdc21cd08345725965169f7976fda492aac7e9a159e075de5b2020aa90b563ee0e777f2dfa7e1b016aee565bbbd0a",
          "sha256": "201bb96e2ca306050b0a1e73920eb1f88375b3a4e7144ab6492010fc3604d140",
          "sha1": "dd5b577c53e5d31f0c843e05567e1f3755dcc0c2",
          "md5": "46d5c66f77b0f666997f64c419cf972b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.4.5-sources.jar",
          "url": "spring-boot-test-3.4.5-sources.jar",
          "size": 174958,
          "sha512": "c9687b6b965235ef91a89246eb5adb5bef13f224d65f8244aacf68eb9a153d69ac99d30a707baea0f7dfd8a329a29ffd72aa9b5c509558102732fadf33ac231f",
          "sha256": "7a26bf04c7ae45c6fe099d602749abb8730cea9d33a5d58652bca57d754ba729",
          "sha1": "93754de413293f2ec81b1a86ff37224c76c3a0fd",
          "md5": "0b7000c660e3f38ca7bdb9cadc368b49"
        }
      ]
    }
  ]
}
