{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-test/2.1.20/kotlin-test-2.1.20.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "jvmJUnit5ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit5-2.1.20.jar",
          "url": "kotlin-test-junit5-2.1.20.jar",
          "size": 5126,
          "sha512": "0caf540e0ee468485492e2bf31cf485e32568f8957c707c4ace190adced97087d95a8d9759a1274c0aaaac151e3afebe89a495946952f90a695fcdbde7783739",
          "sha256": "9da61772c8c2b52f022b9576a53a1b0f87aff1a6372039ce86c2e93b3eeb19cb",
          "sha1": "74f95d1853347f55c06a348c885c0cc37d5d47f9",
          "md5": "649c2fd5d5b93f0d014166e7194c2591"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit5",
          "version": "2.1.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.1.20"
        }
      ]
    },
    {
      "name": "jvmJUnit5RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit5-2.1.20.jar",
          "url": "kotlin-test-junit5-2.1.20.jar",
          "size": 5126,
          "sha512": "0caf540e0ee468485492e2bf31cf485e32568f8957c707c4ace190adced97087d95a8d9759a1274c0aaaac151e3afebe89a495946952f90a695fcdbde7783739",
          "sha256": "9da61772c8c2b52f022b9576a53a1b0f87aff1a6372039ce86c2e93b3eeb19cb",
          "sha1": "74f95d1853347f55c06a348c885c0cc37d5d47f9",
          "md5": "649c2fd5d5b93f0d014166e7194c2591"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit5",
          "version": "2.1.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.1.20"
        }
      ]
    },
    {
      "name": "jvmJUnit5SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-test-junit5-2.1.20-sources.jar",
          "url": "kotlin-test-junit5-2.1.20-sources.jar",
          "size": 2850,
          "sha512": "aa488b547a8587cc2cc004a3e943460a043e926a7cb021d70a3182ff05a1e7d542ba77590d9115db58d9ca1c72bf16bca1eb89fe58f46fb5a0fcf6ec2895a22f",
          "sha256": "891c56d8183d2cd3e912cf250adeca889dba51d02b07fce3015321e08f72b4a2",
          "sha1": "e7609990cba72d2a3ce763011ae79e81b9904b51",
          "md5": "6fc43e36017a96bd097f1858ff8fa394"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit5",
          "version": "2.1.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.1.20"
        }
      ]
    }
  ]
}