server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/merkletreedb
spring.datasource.username=postgres
spring.datasource.password=merkletreedb

# OCN Node
ocn.node.dev = true
ocn.node.signatures = false
ocn.node.url = http://127.0.0.1:8080
ocn.node.apikey = 4b3322c6185278f61f7125fed4eb02d04555dbb8
ocn.node.privatekey = 9df16a85d24a0dab6fb2bc5c57e1068ed47d56d7518e9b0eaf1712cae718ded6
ocn.node.apiPrefix = ocn-v2


# OCN Registry
ocn.registry.indexer.url = https://gateway.thegraph.com/api/subgraphs/id/BTcuNBXNc9kjjNUkCkUGstrGoJGZPsztS6zobMp1Ftmd
ocn.registry.indexer.token = 86dce84a7856a293366ebab0b10f3bd0