server.port=9999

# spring JPA
spring.jpa.open-in-view = false
#spring.jpa.hibernate.ddl-auto=update

# http request handling
server.error.include-stacktrace = never

# logging

# OCN Node
ocn.node.dev = true
ocn.node.signatures = false
ocn.node.url = http://localhost:9999
ocn.node.apikey = randomkey
ocn.node.apiPrefix=ocn-v2

# OCN Hashing as a Service
ocn.haas.enabled = ${OCN_NODE_HAAS_ON:${OCN_HAAS_ENABLED:true}}
ocn.haas.url = ${OCN_NODE_HAAS_URL:${OCN_HAAS_URL:http://localhost:9092/api/v1/public}}


# default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/ocn_node
spring.datasource.username=postgres
spring.datasource.password=minikube

# migrates on startup
spring.jpa.hibernate.ddl-auto=update

# logging (deduplicated)
logging.level.web = ${OCN_WEB_LOGGING_LEVEL:INFO}
logging.level.org.springframework.web.servlet.mvc.method.annotation = WARN
logging.level.org.springframework.web.method = WARN
logging.level.org.springframework.web.servlet = INFO
logging.level.org.hibernate.orm.deprecation = ERROR
logging.level.org.hibernate.orm.connections.pooling = WARN
# optionally control root level if you want less/more verbosity
# logging.level.root=INFO

# curl command logging (enabled for dev/int)
ocn.node.logCurlCommands = true

# Swagger/OpenAPI configuration
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.config-url=/api-docs/swagger-config
springdoc.swagger-ui.url=/api-docs
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true


