spring.application.name=ocn-node

# spring JPA
spring.jpa.open-in-view = false
spring.devtools.add-properties = false

# default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

# OCN Node
ocn.node.dev = ${OCN_NODE_DEV_MODE:false}
ocn.node.signatures = ${OCN_NODE_ENABLE_SIGNING:true}
ocn.node.url = ${OCN_NODE_URL:}
ocn.node.apikey = ${OCN_NODE_ADMIN_KEY:}
ocn.node.apiPrefix: ${OCN_NODE_API:ocn-v2}
ocn.node.countryCode: ${OCN_NODE_COUNTRY_CODE:CH}
ocn.node.partyId: ${OCN_NODE_PARTY_ID:OCN}

# Feature Flags
ocn.features.banulaValidation = ${OCN_FF_BANULA_VALIDATION:false}

# Scheduled Tasks
ocn.node.stillAliveEnabled = ${OCN_NODE_STILL_ALIVE_ENABLED:true}
ocn.node.hubClientInfoSyncEnabled = ${OCN_NODE_HUB_CLIENT_INFO_SYNC_ENABLED:true}
ocn.node.stillAliveRate = ${OCN_NODE_STILL_ALIVE_RATE:900000}
ocn.node.hubClientInfoSyncRate = ${OCN_NODE_HUB_CLIENT_INFO_SYNC_RATE:3600000}

# OCN Hashing as a Service
ocn.haas.enabled = ${OCN_NODE_HAAS_ON:true}
ocn.haas.url = ${OCN_NODE_HAAS_URL:}

# OCN Registry
ocn.registry.indexer.url = ${OCN_REGISTRY_INDEXER_URL:}
ocn.registry.indexer.token = ${OCN_REGISTRY_INDEXER_TOKEN:}
ocn.node.privatekey = ${OCN_NODE_PRIVATE_KEY:}
ocn.node.publicAddress = ${OCN_NODE_PUBLIC_ADDRESS:}

# HCI Publisher
ocn.hci-publisher.countryCode  = ${OCN_HCI_COUNTRY_CODE:DE}
ocn.hci-publisher.partyId  = ${OCN_HCI_COUNTRY_CODE:OLI}

# database
spring.datasource.url=${OCN_NODE_POSTGRES_DATABASE:}
spring.datasource.username=${OCN_NODE_POSTGRES_USER:}
spring.datasource.password=${OCN_NODE_POSTGRES_PASSWORD:}

# migrates on startup
spring.jpa.hibernate.ddl-auto=update

# http request handling
server.error.include-stacktrace = never

# logging
logging.level.web = ${OCN_WEB_LOGGING_LEVEL:INFO}
logging.level.org.springframework.web.servlet.mvc.method.annotation = WARN
logging.level.org.springframework.web.method = WARN
logging.level.org.springframework.web.servlet = INFO
logging.level.org.hibernate.orm.deprecation = ERROR
logging.level.org.hibernate.orm.connections.pooling = WARN

# curl command logging (enable for dev/int, disable for prod)
ocn.node.logCurlCommands = ${OCN_NODE_LOG_CURL_COMMANDS:false}

# Swagger/OpenAPI configuration
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}
springdoc.swagger-ui.config-url=${SERVER_CONTEXT_PATH:}/api-docs/swagger-config
springdoc.swagger-ui.url=${SERVER_CONTEXT_PATH:}/api-docs
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=${SWAGGER_ENABLED:true}


