# Rename this file to application-local-custom.properties and fill in the following values

ocn.node.privatekey = # ocn node private key (ethereum private key for signing)

# OCN Registry
ocn.registry.indexer.url = # https://gateway.thegraph.com/api/subgraphs/id/<subgraph-id>
ocn.registry.indexer.token = # subgraph indexer token
