{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-utils/3.1.3/ktor-utils-3.1.3.module",
    "group": "io.ktor",
    "module": "ktor-utils",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-jvm-3.1.3.jar",
          "url": "ktor-utils-jvm-3.1.3.jar",
          "size": 330425,
          "sha512": "7f258571f3e8d5a660eac7ddb5bf901fed922f5564f04005fced8d3801bcbb73afc5de5c910aa2c29736ef63ddbc37c2a987b793aa0a8c5e3e71ae1ebf4b6e87",
          "sha256": "33333937b98fc0c8e943ee4b10b3ea66b49782dfb569c44c142da4f32d85dffc",
          "sha1": "d2e56dca809c965fa498df86a570fc9ed5b9551f",
          "md5": "644f58679c8999eb26e7696f790f3a4f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-jvm-3.1.3.jar",
          "url": "ktor-utils-jvm-3.1.3.jar",
          "size": 330425,
          "sha512": "7f258571f3e8d5a660eac7ddb5bf901fed922f5564f04005fced8d3801bcbb73afc5de5c910aa2c29736ef63ddbc37c2a987b793aa0a8c5e3e71ae1ebf4b6e87",
          "sha256": "33333937b98fc0c8e943ee4b10b3ea66b49782dfb569c44c142da4f32d85dffc",
          "sha1": "d2e56dca809c965fa498df86a570fc9ed5b9551f",
          "md5": "644f58679c8999eb26e7696f790f3a4f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-utils-jvm-3.1.3-sources.jar",
          "url": "ktor-utils-jvm-3.1.3-sources.jar",
          "size": 88062,
          "sha512": "bed1764aa9766c260df32473c018342462505024bf93c34f5f151400b24679dbe8a701b39b44aa31233b6fe74a047f454d7294426db039da6ec5becd2eb0658c",
          "sha256": "fb6d65c472da44bdb5b82170eccfcfcd32f85cf771c8fd40ed3df585f77b3eb6",
          "sha1": "bb147e8577dc2fcbef282c09080708627ff21299",
          "md5": "f06a2a87e67f489f0d1723bf10c2e07b"
        }
      ]
    }
  ]
}
