{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-kotlin",
    "version": "2.18.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-kotlin-2.18.3.jar",
          "url": "jackson-module-kotlin-2.18.3.jar",
          "size": 186243,
          "sha512": "99aa4116937b842ac2f266b7b7e14553c944d61240c3979fce07b5480fb9354866ea3775981bc1b937544cd1222874e58be7f72bf510e304019cca49ce22760e",
          "sha256": "93ba1638bbab8f8ebc750382477fe05754e78d00bff1473611ec33c305e2a197",
          "sha1": "d79c117605fc157ec32ec9774690bb3e493938ce",
          "md5": "8199d1263cce86d902d2a4e370de9606"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-kotlin-2.18.3.jar",
          "url": "jackson-module-kotlin-2.18.3.jar",
          "size": 186243,
          "sha512": "99aa4116937b842ac2f266b7b7e14553c944d61240c3979fce07b5480fb9354866ea3775981bc1b937544cd1222874e58be7f72bf510e304019cca49ce22760e",
          "sha256": "93ba1638bbab8f8ebc750382477fe05754e78d00bff1473611ec33c305e2a197",
          "sha1": "d79c117605fc157ec32ec9774690bb3e493938ce",
          "md5": "8199d1263cce86d902d2a4e370de9606"
        }
      ]
    }
  ]
}
