{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-serialization",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-metadata-3.1.3.jar",
          "url": "ktor-serialization-3.1.3.jar",
          "size": 4387,
          "sha512": "9c3731fd22ffcc45c508de9b49d1a4941bcbf9174bf68abf72d2f32b741ee0b9f21cbe9f94802b85baf93fec2dc6a5bf11ca8b8745d33a25fb1314f6633e3e72",
          "sha256": "d6eb140251ca5aca5cb69c4ad7ef189353a2bada712f83688384570ab242cd10",
          "sha1": "ceca723ac6c0680d22ddb8ee0267a1fed32c3a91",
          "md5": "6c2aacee3637c1cfa215bae8fb7f4170"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlin-3.1.3-sources.jar",
          "url": "ktor-serialization-3.1.3-sources.jar",
          "size": 3585,
          "sha512": "b4f3ee4444748661cb4af8adb4119570d4b06abb622e7f3926156684e8d70610a7e2422b46dec88ee6d27dbb72f2950d8d6991132d6122042057477ba4b7a098",
          "sha256": "ddc84dd1f279b1c7cd2e476a2b214c1960577116e7abe15c469f8b37fbb46483",
          "sha1": "9947206077a04db4904641c7324fcdc5e5b49ca8",
          "md5": "38a4b496744ca0e47c3a656adb7c0580"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-androidnativearm32/3.1.3/ktor-serialization-androidnativearm32-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-androidnativearm32",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-androidnativearm32/3.1.3/ktor-serialization-androidnativearm32-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-androidnativearm32",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-androidnativearm64/3.1.3/ktor-serialization-androidnativearm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-androidnativearm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-androidnativearm64/3.1.3/ktor-serialization-androidnativearm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-androidnativearm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-androidnativex64/3.1.3/ktor-serialization-androidnativex64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-androidnativex64",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-androidnativex64/3.1.3/ktor-serialization-androidnativex64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-androidnativex64",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-androidnativex86/3.1.3/ktor-serialization-androidnativex86-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-androidnativex86",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-androidnativex86/3.1.3/ktor-serialization-androidnativex86-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-androidnativex86",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosarm64/3.1.3/ktor-serialization-iosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosarm64/3.1.3/ktor-serialization-iosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosarm64/3.1.3/ktor-serialization-iosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iossimulatorarm64/3.1.3/ktor-serialization-iossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iossimulatorarm64/3.1.3/ktor-serialization-iossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iossimulatorarm64/3.1.3/ktor-serialization-iossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosx64/3.1.3/ktor-serialization-iosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosx64/3.1.3/ktor-serialization-iosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosx64/3.1.3/ktor-serialization-iosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-js/3.1.3/ktor-serialization-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-js/3.1.3/ktor-serialization-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-js/3.1.3/ktor-serialization-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-jvm/3.1.3/ktor-serialization-jvm-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-jvm",
        "version": "3.1.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-jvm/3.1.3/ktor-serialization-jvm-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-jvm",
        "version": "3.1.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-jvm/3.1.3/ktor-serialization-jvm-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-jvm",
        "version": "3.1.3"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-linuxarm64/3.1.3/ktor-serialization-linuxarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-linuxarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-linuxarm64/3.1.3/ktor-serialization-linuxarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-linuxarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-linuxx64/3.1.3/ktor-serialization-linuxx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-linuxx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-linuxx64/3.1.3/ktor-serialization-linuxx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-linuxx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosarm64/3.1.3/ktor-serialization-macosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosarm64/3.1.3/ktor-serialization-macosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosarm64/3.1.3/ktor-serialization-macosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosx64/3.1.3/ktor-serialization-macosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosx64/3.1.3/ktor-serialization-macosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosx64/3.1.3/ktor-serialization-macosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-mingwx64/3.1.3/ktor-serialization-mingwx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-mingwx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-mingwx64/3.1.3/ktor-serialization-mingwx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-mingwx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosarm64/3.1.3/ktor-serialization-tvosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosarm64/3.1.3/ktor-serialization-tvosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosarm64/3.1.3/ktor-serialization-tvosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvossimulatorarm64/3.1.3/ktor-serialization-tvossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvossimulatorarm64/3.1.3/ktor-serialization-tvossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvossimulatorarm64/3.1.3/ktor-serialization-tvossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosx64/3.1.3/ktor-serialization-tvosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosx64/3.1.3/ktor-serialization-tvosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosx64/3.1.3/ktor-serialization-tvosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-wasm-js/3.1.3/ktor-serialization-wasm-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-wasm-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-wasm-js/3.1.3/ktor-serialization-wasm-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-wasm-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-wasm-js/3.1.3/ktor-serialization-wasm-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-wasm-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm32/3.1.3/ktor-serialization-watchosarm32-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm32",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm32/3.1.3/ktor-serialization-watchosarm32-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm32",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm32/3.1.3/ktor-serialization-watchosarm32-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm32",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm64/3.1.3/ktor-serialization-watchosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm64/3.1.3/ktor-serialization-watchosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm64/3.1.3/ktor-serialization-watchosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosdevicearm64/3.1.3/ktor-serialization-watchosdevicearm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosdevicearm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosdevicearm64/3.1.3/ktor-serialization-watchosdevicearm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosdevicearm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosdevicearm64/3.1.3/ktor-serialization-watchosdevicearm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosdevicearm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchossimulatorarm64/3.1.3/ktor-serialization-watchossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchossimulatorarm64/3.1.3/ktor-serialization-watchossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchossimulatorarm64/3.1.3/ktor-serialization-watchossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosx64/3.1.3/ktor-serialization-watchosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosx64/3.1.3/ktor-serialization-watchosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosx64/3.1.3/ktor-serialization-watchosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosx64",
        "version": "3.1.3"
      }
    }
  ]
}
