{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http/3.1.3/ktor-http-3.1.3.module",
    "group": "io.ktor",
    "module": "ktor-http",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-jvm-3.1.3.jar",
          "url": "ktor-http-jvm-3.1.3.jar",
          "size": 408860,
          "sha512": "9d4c932b8eb3af2f3d472d71b7c661f3cca1fe38b5b3bda36a9fc721f22ab07bf4a81b50d2e07093fc45e2647b3712136e7ab380314f2bed08104fa3b1d6c4e0",
          "sha256": "8a50d94b46f91bd56580b9169272d6cd636f442032ba078a141da70413465946",
          "sha1": "881944d6731e34f5a90e9d9ac3e942f45d41761c",
          "md5": "eaf2c07a224f81fcd2ddfbc5f335fdc9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-jvm-3.1.3.jar",
          "url": "ktor-http-jvm-3.1.3.jar",
          "size": 408860,
          "sha512": "9d4c932b8eb3af2f3d472d71b7c661f3cca1fe38b5b3bda36a9fc721f22ab07bf4a81b50d2e07093fc45e2647b3712136e7ab380314f2bed08104fa3b1d6c4e0",
          "sha256": "8a50d94b46f91bd56580b9169272d6cd636f442032ba078a141da70413465946",
          "sha1": "881944d6731e34f5a90e9d9ac3e942f45d41761c",
          "md5": "eaf2c07a224f81fcd2ddfbc5f335fdc9"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-http-jvm-3.1.3-sources.jar",
          "url": "ktor-http-jvm-3.1.3-sources.jar",
          "size": 94650,
          "sha512": "4db5ca36b93cd46062307cac3444baeccf433007a17e8f86ee54cbcc449b587c6647589d3552ac38fea8a3994b1f3ade1aea066a748e2f98506a5946cb67ed49",
          "sha256": "ae296f768c5b04cb7a04ee4dc7cd251a40c70080a1058cc2d1521d2a2baf9221",
          "sha1": "e0aa3afc94aa1927a47d24df262873a16f468822",
          "md5": "f7139de6fa3c1aa475d0c6c3acd5ba41"
        }
      ]
    }
  ]
}
