{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-io-core/0.7.0/kotlinx-io-core-0.7.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-io-core",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-core-jvm-0.7.0.jar",
          "url": "kotlinx-io-core-jvm-0.7.0.jar",
          "size": 151554,
          "sha512": "fe04759d2b3b505911b7e0da37089a40f0711ea718a294e72e231c1f5f72c02fb919b5e29d2d58dc310f1bfba2171f0dcb4d6083138ed7f35c020c832fd56f4e",
          "sha256": "6ededc9be4d878aea80c7dd609f91bfc47fcd3d36cc91fd0f3f328fbd6656c8f",
          "sha1": "1d9595ed390f6304ce90a049e6b2f1fab3b408c4",
          "md5": "fe4135408adf234f1283c3c25041c599"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-core-jvm-0.7.0.jar",
          "url": "kotlinx-io-core-jvm-0.7.0.jar",
          "size": 151554,
          "sha512": "fe04759d2b3b505911b7e0da37089a40f0711ea718a294e72e231c1f5f72c02fb919b5e29d2d58dc310f1bfba2171f0dcb4d6083138ed7f35c020c832fd56f4e",
          "sha256": "6ededc9be4d878aea80c7dd609f91bfc47fcd3d36cc91fd0f3f328fbd6656c8f",
          "sha1": "1d9595ed390f6304ce90a049e6b2f1fab3b408c4",
          "md5": "fe4135408adf234f1283c3c25041c599"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-io-core-jvm-0.7.0-sources.jar",
          "url": "kotlinx-io-core-jvm-0.7.0-sources.jar",
          "size": 77756,
          "sha512": "c0f465d0ea997b0f2fab1134fbfaf300568ac631c2c0063652773a670a6e89b392608a8297a5c5f470c028fe151c8b72d746d1a044f20c75ee7bdfe385c95a2a",
          "sha256": "b443703c2b34f7c2eeb4a850392c9a282b947ef3d78de608453486cce735d976",
          "sha1": "f19ae5c8d4fb0ef5b5da8f116e7edeb3d4bbfd5a",
          "md5": "d607cf0956e6e371933c74fbbbb4dce8"
        }
      ]
    }
  ]
}
