{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-network",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-metadata-3.1.3.jar",
          "url": "ktor-network-3.1.3.jar",
          "size": 90048,
          "sha512": "04ff09d1c0690a00118b2e8785f88c915868f6612b03ac2d60e63bfff26861e9d8378648155041a50060de9ddbcf8fe720aca770a8b20d882139c4aa3702798a",
          "sha256": "8ea92ab549ace78ad73023a0743867ce10c4bc7e87b894bc4dd3ddf445a6877a",
          "sha1": "640f8933c4afe6a0ece874ec7cf6c414a502ac60",
          "md5": "2ed9e1e4f734831c80c25196ecae9014"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-network-kotlin-3.1.3-sources.jar",
          "url": "ktor-network-3.1.3-sources.jar",
          "size": 59121,
          "sha512": "2b8c2196a48d662a5c51d20a7547dd814c69aed29c0475cdecb0d2dd555275cf5a4df3ff9ed4b1b8eaeb685e0b78dbb394fd9c83ab554e491e829cf290285df5",
          "sha256": "e79da6b3cc35eae739dbf355f28a44278ff2b6bc1b8e0cd89a7d7837f151b7e9",
          "sha1": "67c191caa61e38e12dbfa32f6b73e77542c42245",
          "md5": "3d58bce57df80b1978afd6b59b5e0f60"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-androidnativearm32/3.1.3/ktor-network-androidnativearm32-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-androidnativearm32",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-androidnativearm32/3.1.3/ktor-network-androidnativearm32-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-androidnativearm32",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-androidnativearm64/3.1.3/ktor-network-androidnativearm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-androidnativearm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-androidnativearm64/3.1.3/ktor-network-androidnativearm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-androidnativearm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-androidnativex64/3.1.3/ktor-network-androidnativex64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-androidnativex64",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-androidnativex64/3.1.3/ktor-network-androidnativex64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-androidnativex64",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-androidnativex86/3.1.3/ktor-network-androidnativex86-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-androidnativex86",
        "version": "3.1.3"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-androidnativex86/3.1.3/ktor-network-androidnativex86-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-androidnativex86",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosarm64/3.1.3/ktor-network-iosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-iosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosarm64/3.1.3/ktor-network-iosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-iosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosarm64/3.1.3/ktor-network-iosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-iosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iossimulatorarm64/3.1.3/ktor-network-iossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-iossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iossimulatorarm64/3.1.3/ktor-network-iossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-iossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iossimulatorarm64/3.1.3/ktor-network-iossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-iossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosx64/3.1.3/ktor-network-iosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-iosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosx64/3.1.3/ktor-network-iosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-iosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosx64/3.1.3/ktor-network-iosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-iosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-network-js/3.1.3/ktor-network-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-network-js/3.1.3/ktor-network-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-network-js/3.1.3/ktor-network-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-network-jvm/3.1.3/ktor-network-jvm-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-jvm",
        "version": "3.1.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-network-jvm/3.1.3/ktor-network-jvm-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-jvm",
        "version": "3.1.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-network-jvm/3.1.3/ktor-network-jvm-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-jvm",
        "version": "3.1.3"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-linuxarm64/3.1.3/ktor-network-linuxarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-linuxarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-linuxarm64/3.1.3/ktor-network-linuxarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-linuxarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-linuxx64/3.1.3/ktor-network-linuxx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-linuxx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-linuxx64/3.1.3/ktor-network-linuxx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-linuxx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosarm64/3.1.3/ktor-network-macosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-macosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosarm64/3.1.3/ktor-network-macosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-macosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosarm64/3.1.3/ktor-network-macosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-macosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosx64/3.1.3/ktor-network-macosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-macosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosx64/3.1.3/ktor-network-macosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-macosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosx64/3.1.3/ktor-network-macosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-macosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-mingwx64/3.1.3/ktor-network-mingwx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-mingwx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-mingwx64/3.1.3/ktor-network-mingwx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-mingwx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosarm64/3.1.3/ktor-network-tvosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosarm64/3.1.3/ktor-network-tvosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosarm64/3.1.3/ktor-network-tvosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvossimulatorarm64/3.1.3/ktor-network-tvossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-tvossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvossimulatorarm64/3.1.3/ktor-network-tvossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-tvossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvossimulatorarm64/3.1.3/ktor-network-tvossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-tvossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosx64/3.1.3/ktor-network-tvosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosx64/3.1.3/ktor-network-tvosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosx64/3.1.3/ktor-network-tvosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-network-wasm-js/3.1.3/ktor-network-wasm-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-wasm-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-network-wasm-js/3.1.3/ktor-network-wasm-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-wasm-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-network-wasm-js/3.1.3/ktor-network-wasm-js-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-wasm-js",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm32/3.1.3/ktor-network-watchosarm32-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm32",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm32/3.1.3/ktor-network-watchosarm32-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm32",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm32/3.1.3/ktor-network-watchosarm32-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm32",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm64/3.1.3/ktor-network-watchosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm64/3.1.3/ktor-network-watchosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm64/3.1.3/ktor-network-watchosarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosdevicearm64/3.1.3/ktor-network-watchosdevicearm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosdevicearm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosdevicearm64/3.1.3/ktor-network-watchosdevicearm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosdevicearm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosdevicearm64/3.1.3/ktor-network-watchosdevicearm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosdevicearm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchossimulatorarm64/3.1.3/ktor-network-watchossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchossimulatorarm64/3.1.3/ktor-network-watchossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchossimulatorarm64/3.1.3/ktor-network-watchossimulatorarm64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchossimulatorarm64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosx64/3.1.3/ktor-network-watchosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosx64/3.1.3/ktor-network-watchosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosx64",
        "version": "3.1.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosx64/3.1.3/ktor-network-watchosx64-3.1.3.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosx64",
        "version": "3.1.3"
      }
    }
  ]
}
