{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-websocket-serialization/3.1.3/ktor-websocket-serialization-3.1.3.module",
    "group": "io.ktor",
    "module": "ktor-websocket-serialization",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websocket-serialization-jvm-3.1.3.jar",
          "url": "ktor-websocket-serialization-jvm-3.1.3.jar",
          "size": 6992,
          "sha512": "cb6e4e11da8125c3e669399fed46671e1c2b1e67b63cbed9b428df21f8b312e7df3dde1dfda55a98b8005b897af8e291e3cb1f5c000874cea435317e9fda01c4",
          "sha256": "67f0f566e2ed51717f6ed55f6d2b4dee1c84be4ea2cd96fc636d0bdf0fd43067",
          "sha1": "e89460b5597c8cbe0fc22766c6cf6fd25af5326b",
          "md5": "9b9e6786c2ef95a453aec147ff9f8e01"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websocket-serialization-jvm-3.1.3.jar",
          "url": "ktor-websocket-serialization-jvm-3.1.3.jar",
          "size": 6992,
          "sha512": "cb6e4e11da8125c3e669399fed46671e1c2b1e67b63cbed9b428df21f8b312e7df3dde1dfda55a98b8005b897af8e291e3cb1f5c000874cea435317e9fda01c4",
          "sha256": "67f0f566e2ed51717f6ed55f6d2b4dee1c84be4ea2cd96fc636d0bdf0fd43067",
          "sha1": "e89460b5597c8cbe0fc22766c6cf6fd25af5326b",
          "md5": "9b9e6786c2ef95a453aec147ff9f8e01"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-websocket-serialization-jvm-3.1.3-sources.jar",
          "url": "ktor-websocket-serialization-jvm-3.1.3-sources.jar",
          "size": 2326,
          "sha512": "e7fe8c5d0f1bab74755507fcfc8214bec60935736c0dc1ad54f1076115ca58f63d40702f38503b3b2a3b9d8d02ba55b91d62f5d4e326b9bcb5c454859258e3f8",
          "sha256": "e186e6ac4d88ce296ef51d91684444ca0002b4b7761a8dcd2fe55ef1dc8a7b75",
          "sha1": "4a023f031c84e174cfcb56892d01b37de32011e9",
          "md5": "0dca7e417fd69fd93f87b73d37846741"
        }
      ]
    }
  ]
}
