oli-app:
  fullnameOverride: "ocn-node-v2-prod"

  image:
    tag: "v1.4.5-rc"

  ingress:
    hosts:
      - host: banula.oli-system.com
    tls:
      - secretName: banula-tls
        hosts:
          - banula.oli-system.com
