oli-app:
  fullnameOverride: "ocn-node-v2-dev"
  image:
    tag: "develop-ecd757d"
  ingress:
    hosts:
      - host: banula-dev.oli-system.com
    tls:
      - secretName: banula-dev-tls
        hosts:
          - banula-dev.oli-system.com
    features:
      router:
        routes:
          exposeCommon: false
          exposeAll: true
