oli-app:
  fullnameOverride: "ocn-node-v2-int"

  image:
    tag: "main"

  ingress:
    hosts:
      - host: banula-int.oli-system.com
    tls:
      - secretName: banula-int-tls
        hosts:
          - banula-int.oli-system.com
    features:
      router:
        routes:
          exposeCommon: false
          exposeAll: true
