{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-network/3.1.3/ktor-network-3.1.3.module",
    "group": "io.ktor",
    "module": "ktor-network",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-jvm-3.1.3.jar",
          "url": "ktor-network-jvm-3.1.3.jar",
          "size": 194224,
          "sha512": "28a6bb7dc525ac56b07871dd1b8fadde9ff36bbdd0172392e264b170fad666acefc44fbc032b12dac95d947ee50e683ba3fbba819f8f3dd74f1edeeb475203bc",
          "sha256": "fa4e6165b5ad4bf5db337ebd5f16f9b596dc5e401fbea343b9deacb6138240af",
          "sha1": "6c3bc178f66874bf4883dd1ac7e8a92871b02a4f",
          "md5": "4895612ad285903168e26c21266db244"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-jvm-3.1.3.jar",
          "url": "ktor-network-jvm-3.1.3.jar",
          "size": 194224,
          "sha512": "28a6bb7dc525ac56b07871dd1b8fadde9ff36bbdd0172392e264b170fad666acefc44fbc032b12dac95d947ee50e683ba3fbba819f8f3dd74f1edeeb475203bc",
          "sha256": "fa4e6165b5ad4bf5db337ebd5f16f9b596dc5e401fbea343b9deacb6138240af",
          "sha1": "6c3bc178f66874bf4883dd1ac7e8a92871b02a4f",
          "md5": "4895612ad285903168e26c21266db244"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-network-jvm-3.1.3-sources.jar",
          "url": "ktor-network-jvm-3.1.3-sources.jar",
          "size": 40769,
          "sha512": "9ae740b21dcc2af514ca563aadb944ddec63a7b711d7cf2c0a8ddd6ff97d981b59c04c0e15e88628f7832950a387393b7879f70bf0883c5ad0b43654ab08ba82",
          "sha256": "118e7758926fd0a977c73cc41ba00e1f1b577e6d56f818e20eb1d49e793d2b0a",
          "sha1": "ed9ad0cb25f7a0bcd4ab56fb57636d3b4b47b152",
          "md5": "b2240b334f9f47d3beb414aa5b8a1b25"
        }
      ]
    }
  ]
}
