{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aspects",
    "version": "6.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.2.6.jar",
          "url": "spring-aspects-6.2.6.jar",
          "size": 49860,
          "sha512": "21782cfe3ab101cb2364e41f6d881285447e3c93b60b80f4fd6de0ec8a2125da8837be2d8f6827abd14f186a2e9930e00ed9db06d103bfe3642d03e55eb82372",
          "sha256": "00b16e2b501af661dff20ebf559e5958413d58435551ff38fcebba5adbf4c9e6",
          "sha1": "2bb7fe48b4fef28af71be32815200c19ac95f783",
          "md5": "1ef239f00c8a2ed1f96d85f9fde2e605"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.2.6.jar",
          "url": "spring-aspects-6.2.6.jar",
          "size": 49860,
          "sha512": "21782cfe3ab101cb2364e41f6d881285447e3c93b60b80f4fd6de0ec8a2125da8837be2d8f6827abd14f186a2e9930e00ed9db06d103bfe3642d03e55eb82372",
          "sha256": "00b16e2b501af661dff20ebf559e5958413d58435551ff38fcebba5adbf4c9e6",
          "sha1": "2bb7fe48b4fef28af71be32815200c19ac95f783",
          "md5": "1ef239f00c8a2ed1f96d85f9fde2e605"
        }
      ]
    }
  ]
}
