{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-sse/3.1.3/ktor-sse-3.1.3.module",
    "group": "io.ktor",
    "module": "ktor-sse",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-sse-jvm-3.1.3.jar",
          "url": "ktor-sse-jvm-3.1.3.jar",
          "size": 8378,
          "sha512": "9687af23d0cedb0e16d5057d79fd3878c60dba4dd085f9b4124602ca00b07bbc26eb735df3ac385c48794fce6ecd72cd43e404ed8512ad5ac99b39983b0bf7a2",
          "sha256": "a2ae8a338bb1d446d16dcfea2189ef5a5be31a88123b3879562b7955667a5639",
          "sha1": "923aed31a9c222641d0dcb1c793d3c8d03f976a3",
          "md5": "dabacf0f540f0acf26a5a37c6b6e4ddf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-sse-jvm-3.1.3.jar",
          "url": "ktor-sse-jvm-3.1.3.jar",
          "size": 8378,
          "sha512": "9687af23d0cedb0e16d5057d79fd3878c60dba4dd085f9b4124602ca00b07bbc26eb735df3ac385c48794fce6ecd72cd43e404ed8512ad5ac99b39983b0bf7a2",
          "sha256": "a2ae8a338bb1d446d16dcfea2189ef5a5be31a88123b3879562b7955667a5639",
          "sha1": "923aed31a9c222641d0dcb1c793d3c8d03f976a3",
          "md5": "dabacf0f540f0acf26a5a37c6b6e4ddf"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-sse-jvm-3.1.3-sources.jar",
          "url": "ktor-sse-jvm-3.1.3-sources.jar",
          "size": 1802,
          "sha512": "41429733cbafadd03cbb1831acf3e488832be89324942330849c333c39b46801d273bd1cc324d90db2cdc5ab1e3ab7acfe37552d2c3d6bcf4d60d07eddd7dc1a",
          "sha256": "c68c47d49e1faab58785b6646363a0c634e641c866c7030edc3f44be4c85ec9c",
          "sha1": "ceaf6f378fa7c0005625aff6a95e975bcea932e5",
          "md5": "0d6f9b4c42ca260589a9cc8387193271"
        }
      ]
    }
  ]
}
