{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-network-tls/3.1.3/ktor-network-tls-3.1.3.module",
    "group": "io.ktor",
    "module": "ktor-network-tls",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-jvm-3.1.3.jar",
          "url": "ktor-network-tls-jvm-3.1.3.jar",
          "size": 197790,
          "sha512": "900f1ba40e7c21691ade34977f25536f28d70611bfcc81dedd9abd01fb9a279469026b11d0a6208ba5a0771429ef0423fe5dd528995c5a8c358b67935406df52",
          "sha256": "f67507a3e8bf52aa08d753682e6cdda0194e3abe750118b99c9336953e598be9",
          "sha1": "87db32e3555e59384450316976b1646a1748e8c9",
          "md5": "66f8a43b495f0b07aebfaff679afc1eb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-jvm-3.1.3.jar",
          "url": "ktor-network-tls-jvm-3.1.3.jar",
          "size": 197790,
          "sha512": "900f1ba40e7c21691ade34977f25536f28d70611bfcc81dedd9abd01fb9a279469026b11d0a6208ba5a0771429ef0423fe5dd528995c5a8c358b67935406df52",
          "sha256": "f67507a3e8bf52aa08d753682e6cdda0194e3abe750118b99c9336953e598be9",
          "sha1": "87db32e3555e59384450316976b1646a1748e8c9",
          "md5": "66f8a43b495f0b07aebfaff679afc1eb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-network-tls-jvm-3.1.3-sources.jar",
          "url": "ktor-network-tls-jvm-3.1.3-sources.jar",
          "size": 39186,
          "sha512": "dde4c51a42f75986dc8d60c0c3ead2e9882f1b2324117cd9538fd454a2a58e94e522996f22c75535815c476c78c76168455f9aef8ba0a6e9419835cecd557e96",
          "sha256": "10bd017eeee0f9f616c9a11bc4467565e1ce89273f251b4e247a718afa558de3",
          "sha1": "cbc8b6c39228c4a627a52f42fc018eb10d5f86ad",
          "md5": "f108258220945bad4cb28b336868483a"
        }
      ]
    }
  ]
}
