{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "3.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.6.13.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.4.5.jar",
          "url": "spring-boot-starter-data-jpa-3.4.5.jar",
          "size": 4762,
          "sha512": "519cfa38e78e5ea942016ab6b4eb9b436b4da91b750607cb2f8f376c9fd4e62c93ad2206413462159f243b950d0fd051e993e227638a44b09dae320d3d14c902",
          "sha256": "2f1a31dd9a475a5750ee58ae9bdd50e75ff72e1cfbfe5a67ab8cd4d9f9ca37e3",
          "sha1": "c6ef06dfef1b02f3e3f82d67118d3944672e7d49",
          "md5": "bf530f5ec5ebb385af0062d9bc27b72b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.6.13.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.4.5.jar",
          "url": "spring-boot-starter-data-jpa-3.4.5.jar",
          "size": 4762,
          "sha512": "519cfa38e78e5ea942016ab6b4eb9b436b4da91b750607cb2f8f376c9fd4e62c93ad2206413462159f243b950d0fd051e993e227638a44b09dae320d3d14c902",
          "sha256": "2f1a31dd9a475a5750ee58ae9bdd50e75ff72e1cfbfe5a67ab8cd4d9f9ca37e3",
          "sha1": "c6ef06dfef1b02f3e3f82d67118d3944672e7d49",
          "md5": "bf530f5ec5ebb385af0062d9bc27b72b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.4.5-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-3.4.5-javadoc.jar",
          "size": 4762,
          "sha512": "519cfa38e78e5ea942016ab6b4eb9b436b4da91b750607cb2f8f376c9fd4e62c93ad2206413462159f243b950d0fd051e993e227638a44b09dae320d3d14c902",
          "sha256": "2f1a31dd9a475a5750ee58ae9bdd50e75ff72e1cfbfe5a67ab8cd4d9f9ca37e3",
          "sha1": "c6ef06dfef1b02f3e3f82d67118d3944672e7d49",
          "md5": "bf530f5ec5ebb385af0062d9bc27b72b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.4.5-sources.jar",
          "url": "spring-boot-starter-data-jpa-3.4.5-sources.jar",
          "size": 4762,
          "sha512": "519cfa38e78e5ea942016ab6b4eb9b436b4da91b750607cb2f8f376c9fd4e62c93ad2206413462159f243b950d0fd051e993e227638a44b09dae320d3d14c902",
          "sha256": "2f1a31dd9a475a5750ee58ae9bdd50e75ff72e1cfbfe5a67ab8cd4d9f9ca37e3",
          "sha1": "c6ef06dfef1b02f3e3f82d67118d3944672e7d49",
          "md5": "bf530f5ec5ebb385af0062d9bc27b72b"
        }
      ]
    }
  ]
}
