{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-io/3.1.3/ktor-io-3.1.3.module",
    "group": "io.ktor",
    "module": "ktor-io",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-io-jvm-3.1.3.jar",
          "url": "ktor-io-jvm-3.1.3.jar",
          "size": 279696,
          "sha512": "1a50ea028e11cd288d49d521f705c87b10175cb4a5a051fe564b38bb9b16aa3c7996e81063ca5a9224cef88330a10d116372e01c97cee700d7f364e4a8a4294f",
          "sha256": "bb2fb6c00afaa34b539cb30e7584d37bfcba171c266bbdb9990e003579dc24c1",
          "sha1": "24be84462406569be2359e5a013a4fa8770a1c0c",
          "md5": "79c1ed2cc26872cb8e62bc5c6a7d1617"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-io-jvm-3.1.3.jar",
          "url": "ktor-io-jvm-3.1.3.jar",
          "size": 279696,
          "sha512": "1a50ea028e11cd288d49d521f705c87b10175cb4a5a051fe564b38bb9b16aa3c7996e81063ca5a9224cef88330a10d116372e01c97cee700d7f364e4a8a4294f",
          "sha256": "bb2fb6c00afaa34b539cb30e7584d37bfcba171c266bbdb9990e003579dc24c1",
          "sha1": "24be84462406569be2359e5a013a4fa8770a1c0c",
          "md5": "79c1ed2cc26872cb8e62bc5c6a7d1617"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-io-jvm-3.1.3-sources.jar",
          "url": "ktor-io-jvm-3.1.3-sources.jar",
          "size": 65536,
          "sha512": "dcd00e38c97eed2ceee83690dc27e5c022ed2b784544b8c773abf3d277e7fb3242f44168d8724c30aa4cd54e06e21d0a97d4281579a231ae5a510033b02e9f46",
          "sha256": "90ae730b9e0a0ac3f20a53e12247d6f27ae3359118d0b7329aa5a1f896ff6c74",
          "sha1": "70650ad7ce9aba8480322066193c5f629a17eab1",
          "md5": "d577266c800a962ed98f3979d82536b6"
        }
      ]
    }
  ]
}
