{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-events/3.1.3/ktor-events-3.1.3.module",
    "group": "io.ktor",
    "module": "ktor-events",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-events-jvm-3.1.3.jar",
          "url": "ktor-events-jvm-3.1.3.jar",
          "size": 6390,
          "sha512": "84f19ac8dac91b422653b2f553ab16615b607e193e97e2c679a0c35f6964032c374a6adce5f3681e2b7735b6f9d7b1bf45ab9124c7285227a4a18f52703526d3",
          "sha256": "da7069c6e78809d7c37d104e415613cbd4cd5cec1ed54a332cb64ef6a864a060",
          "sha1": "ebce4d94edc41cd8ca119da9152af8aa63f706c7",
          "md5": "53aa69566302063d3a78385209d1c059"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-events-jvm-3.1.3.jar",
          "url": "ktor-events-jvm-3.1.3.jar",
          "size": 6390,
          "sha512": "84f19ac8dac91b422653b2f553ab16615b607e193e97e2c679a0c35f6964032c374a6adce5f3681e2b7735b6f9d7b1bf45ab9124c7285227a4a18f52703526d3",
          "sha256": "da7069c6e78809d7c37d104e415613cbd4cd5cec1ed54a332cb64ef6a864a060",
          "sha1": "ebce4d94edc41cd8ca119da9152af8aa63f706c7",
          "md5": "53aa69566302063d3a78385209d1c059"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-events-jvm-3.1.3-sources.jar",
          "url": "ktor-events-jvm-3.1.3-sources.jar",
          "size": 2148,
          "sha512": "7daa847643accbec0d0ff76b1e315cbc1ba8ec279cf92e877b3f1861bc404fb80a8d13e760e1ab8147140475b64fb2be0713189f306fa92873ac9263fea93226",
          "sha256": "25a4d89461d074f84b3f77d8bfe875832adfe744c83aee283f4586f37acdffc3",
          "sha1": "40750b1d65bf1bb0e2740bc83fc54f83b5333808",
          "md5": "97598efdaf9dcc0f013164ec1cce5b35"
        }
      ]
    }
  ]
}
