apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocn-node-v2-prod
  namespace: argocd
  labels:
    repo: ocn-node-v2
spec:
  project: banula
  source:
    repoURL: https://github.com/olisystems/ocn-node-v2.git
    targetRevision: v.1.0.0
    path: infra/helm
    helm:
      parameters:
        - name: oli-app.image.tag
          value: "v.1.0.0"
      valueFiles:
        - values.yaml
        - values.prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: banula-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
