{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "3.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.4.5.jar",
          "url": "spring-boot-test-autoconfigure-3.4.5.jar",
          "size": 227013,
          "sha512": "bbedd430212434012fa069d0d2a441ae6b693d866324f196677c9036cc1634adb52edc11e21571761747a7d1909abb20e6ede483916cebaea53bbedd9be81668",
          "sha256": "b4f2a27c753277d1c49abcc3d874f502acf0c2dcd2568416617aa79c4f1edf81",
          "sha1": "c09f2ad6c025325b151ed1643cbbad93217eecfb",
          "md5": "22bdcfec875ef5aa3a920e15edd104c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.4.5.jar",
          "url": "spring-boot-test-autoconfigure-3.4.5.jar",
          "size": 227013,
          "sha512": "bbedd430212434012fa069d0d2a441ae6b693d866324f196677c9036cc1634adb52edc11e21571761747a7d1909abb20e6ede483916cebaea53bbedd9be81668",
          "sha256": "b4f2a27c753277d1c49abcc3d874f502acf0c2dcd2568416617aa79c4f1edf81",
          "sha1": "c09f2ad6c025325b151ed1643cbbad93217eecfb",
          "md5": "22bdcfec875ef5aa3a920e15edd104c2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.4.5-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-3.4.5-javadoc.jar",
          "size": 492947,
          "sha512": "bde134b4592da622bb6d19b9f71f045c581eb360a2256028c759dd5d15b68d1752822394af7b7a7af058f67d5f842aa50bcaefbe20bd582364e0734238eb8edb",
          "sha256": "c35a8ee7456a8c7cdd8c24be8b9baf2a0fa81a20c587518aa40b213b41bbc390",
          "sha1": "36af2f09975d8f3fce17a16a5967be766be98065",
          "md5": "bdeaf5b7dd784057dcdb4d44b719924d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.4.5-sources.jar",
          "url": "spring-boot-test-autoconfigure-3.4.5-sources.jar",
          "size": 226629,
          "sha512": "299572a95c86f47e8e3dbe7e472404c0c935b35b32f49994d34b7841f1fbcc0985d02350205d9bffbefac98917d7e943171af6a1e3f17c4bbae4b33da0328814",
          "sha256": "73ddeab297ea1d21127ff5b76e927a4f2aaf6373def138eafd75dd47f2a7fe1b",
          "sha1": "41be31af61b4ffdf0ed0ae5ee5ec2aa509c9ed4f",
          "md5": "5036e0db9c0da414b5af4fe525243970"
        }
      ]
    }
  ]
}
