name: Checks

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: olisystems/actions/java/setup@main

      - name: Build and test
        run: ./gradlew build
